// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

type SessionView struct {
	ID        string
	Name      string
	WorkDir   string
	State     string
	Type      string // "claude", "terminal", "discovered"
	Owned     bool
	GroupName string // non-empty if session is in a split tab group
}

type NotificationView struct {
	ID          int64
	SessionID   string
	SessionName string
	WorkDir     string
	EventType   string
	Message     string
	Timestamp   string
	TimeAgo     string
}

type PageData struct {
	Sessions      []SessionView
	History       []SessionView
	Notifications []NotificationView
	UnreadCount   int
}

func Index(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app\"><header class=\"topbar\"><h1 class=\"topbar-title\">websessions</h1><div class=\"topbar-actions\"><div class=\"shortcuts-wrapper\"><button class=\"shortcuts-btn\" onclick=\"window.websessions.toggleShortcuts()\" title=\"Keyboard shortcuts\">?</button><div id=\"shortcuts-dropdown\" class=\"dropdown shortcuts-dropdown\"><div class=\"shortcuts-panel\"><div class=\"shortcuts-title\">Keyboard Shortcuts</div><div class=\"shortcut-row\"><kbd>Ctrl+N</kbd> <span>New session</span></div><div class=\"shortcut-row\"><kbd>Ctrl+T</kbd> <span>New terminal</span></div><div class=\"shortcut-row\"><kbd>Ctrl+W</kbd> <span>Close tab</span></div><div class=\"shortcut-row\"><kbd>Ctrl+]</kbd> <span>Next tab</span></div><div class=\"shortcut-row\"><kbd>Ctrl+[</kbd> <span>Previous tab</span></div><div class=\"shortcut-row\"><kbd>Ctrl+1-9</kbd> <span>Go to tab</span></div><div class=\"shortcut-row\"><kbd>Ctrl+=</kbd> <span>Zoom in</span></div><div class=\"shortcut-row\"><kbd>Ctrl+-</kbd> <span>Zoom out</span></div><div class=\"shortcut-row\"><kbd>Ctrl+0</kbd> <span>Reset zoom</span></div></div></div></div><button class=\"theme-toggle\" onclick=\"window.websessions.toggleTheme()\" title=\"Toggle light/dark theme\" id=\"theme-toggle-btn\">&#9790;</button> <a href=\"/settings\" class=\"settings-link\" title=\"Settings\">&#9881;</a><div class=\"notification-wrapper\"><button class=\"notification-bell\" onclick=\"window.websessions.toggleNotifications()\"><span class=\"bell-icon\">&#128276;</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.UnreadCount > 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span class=\"badge\" id=\"notif-badge\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(itoa(data.UnreadCount))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/index.templ`, Line: 62, Col: 69}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</button><div id=\"notification-dropdown\" class=\"dropdown\"></div></div></div></header><div class=\"main\"><aside id=\"sidebar\" class=\"sidebar\" hx-get=\"/sidebar\" hx-trigger=\"every 30s\" hx-swap=\"innerHTML\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Sidebar(data.Sessions, data.History).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</aside><div class=\"sidebar-resize-handle\" id=\"sidebar-resize-handle\"></div><div class=\"content\"><div id=\"tab-bar\" class=\"tab-bar\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Tabs(nil, "").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div id=\"terminal-area\" class=\"terminal-area\"><div class=\"empty-state\"><p>Select a session from the sidebar or create a new one</p><p class=\"empty-state-hint\">Running Claude Code sessions are discovered automatically</p><p class=\"empty-state-keys\"><kbd>Ctrl+N</kbd> new session <kbd>Ctrl+T</kbd> terminal <kbd>Ctrl+Tab</kbd> cycle tabs</p></div></div></div></div><footer class=\"footer\"><button class=\"new-session-btn\" hx-get=\"/sessions/new\" hx-target=\"#modal\" hx-swap=\"innerHTML\">+ New Session</button> <button class=\"new-terminal-btn\" onclick=\"window.websessions.openTerminal()\">&#9002; Terminal</button><div class=\"footer-spacer\"></div><button class=\"kill-all-btn\" onclick=\"window.websessions.killAllSessions()\" title=\"Kill all running sessions\">&#9632; Kill All</button></footer><div id=\"modal\"></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("websessions").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func itoa(n int) string {
	return fmt.Sprintf("%d", n)
}

var _ = templruntime.GeneratedTemplate
