// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NewTeamModal(defaultDir string, recentDirs []string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"modal-overlay\" onclick=\"this.remove()\"><div class=\"modal-content\" onclick=\"event.stopPropagation()\"><h2>Create Agent Team</h2><p class=\"modal-hint\">Spawn a Claude Code session as team lead with agent teams enabled. The lead will create and coordinate teammates based on your prompt.</p><form id=\"new-team-form\" hx-post=\"/teams\" hx-swap=\"none\"><div class=\"form-group\"><label for=\"team-name\">Team Name</label> <input type=\"text\" id=\"team-name\" name=\"name\" placeholder=\"my-refactor-team\" required></div><div class=\"form-group\" style=\"position:relative;\"><label for=\"team-work-dir\">Working Directory</label> <input type=\"text\" id=\"team-work-dir\" name=\"work_dir\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(defaultDir)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/newteam.templ`, Line: 15, Col: 77}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" required autocomplete=\"off\" oninput=\"window.websessions.dirAutocomplete(this)\"><div id=\"team-dir-suggestions\" class=\"dir-suggestions\"></div></div><div class=\"form-group\"><label for=\"team-prompt\">Team Prompt</label> <textarea id=\"team-prompt\" name=\"prompt\" rows=\"5\" placeholder=\"Create an agent team to... (describe the task, team structure, and roles)\" required></textarea></div><div class=\"form-group\"><label for=\"team-model\">Teammate Model (optional)</label> <select id=\"team-model\" name=\"model\"><option value=\"\">Default (same as lead)</option> <option value=\"sonnet\">Sonnet</option> <option value=\"opus\">Opus</option> <option value=\"haiku\">Haiku</option></select></div><div class=\"form-actions\"><button type=\"button\" class=\"btn-cancel\" onclick=\"this.closest('.modal-overlay').remove()\">Cancel</button> <button type=\"submit\" class=\"btn-create\">Create Team</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
